[package]
name = "refmt"
version = "0.1.0"
edition = "2024"

[dependencies]
rb-syntax.workspace = true
rb-diagnostic.workspace = true

clap = { version = "4.5.50", features = ["derive"] }

[dev-dependencies]
rb-test.workspace = true
