[package]
name = "rebar"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "rb-parser",
  "rb-syntax",
  "rb-typer",
  "rb-test",
  "rb-build",
]

[workspace.dependencies]
rb-test = { path = "rb-test" }
rb-build = { path = "rb-build" }
rb-parser = { path = "rb-parser" }
