[package]
name = "rebar"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "rb-build",
  "rb-test",
  "rb-parser",
  "rb-syntax",
  "rb-hir",
  "rb-typer",
  "rb-mir",
  "rb-runtime",
]

[workspace.dependencies]
rb-test = { path = "rb-test" }
rb-build = { path = "rb-build" }
rb-parser = { path = "rb-parser" }
rb-syntax = { path = "rb-syntax" }
rb-hir = { path = "rb-hir" }
rb-typer = { path = "rb-typer" }
rb-mir = { path = "rb-mir" }
