[package]
name = "rb-hir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
rb-diagnostic.workspace = true

la-arena = "0.3.1"
