[package]
name = "rb-jit"
version = "0.1.0"
edition = "2021"

[dependencies]
rb-syntax.workspace = true
rb-diagnostic.workspace = true
rb-mir.workspace = true

cranelift = "0.108.1"
cranelift-jit = "0.108.1"
cranelift-module = "0.108.1"
cranelift-native = "0.108.1"
