[package]
name = "rb-diagnostic"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
la-arena = "0.3.1"
line-index = "0.1.2"
parking_lot = "0.12.5"
rb-syntax.workspace = true

[features]
test = []
