[package]
name = "rb-hir-lower"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
rb-diagnostic.workspace = true
rb-syntax.workspace = true
rb-hir.workspace = true

[features]
test = []
